/*
 * ============================================================
 * Current facility occupancy
 * ============================================================
 *
 * Stores only the latest accepted occupancy state for each
 * medical facility.
 *
 * Exactly one row is allowed per facility.
 */
CREATE TABLE facility_current_occupancy (
    facility_id BIGINT PRIMARY KEY,

    /*
     * The event that produced this current state.
     */
    last_event_id UUID NOT NULL,

    /*
     * Device or system that produced the occupancy reading.
     *
     * Example:
     * facility-device-dam-hosp-001
     */
    source_device_id TEXT NOT NULL,

    /*
     * Monotonically increasing number generated by the source.
     */
    sequence_number BIGINT NOT NULL,

    total_beds INTEGER NOT NULL,

    occupied_beds INTEGER NOT NULL,

    /*
     * Automatically calculated by PostgreSQL:
     *
     * available_beds = total_beds - occupied_beds
     */
    available_beds INTEGER
        GENERATED ALWAYS AS (
            total_beds - occupied_beds
        ) STORED,

    /*
     * Automatically calculated by PostgreSQL:
     *
     * occupancy percentage =
     * occupied beds / total beds * 100
     */
    occupancy_percentage NUMERIC(7, 4)
        GENERATED ALWAYS AS (
            (
                occupied_beds::NUMERIC
                * 100
            )
            /
            total_beds::NUMERIC
        ) STORED,

    /*
     * The project has only two facility states:
     *
     * greater than 90 percent => RED
     * 90 percent or less      => GREEN
     */
    status TEXT
        GENERATED ALWAYS AS (
            CASE
                WHEN (
                    occupied_beds::NUMERIC
                    * 100
                )
                /
                total_beds::NUMERIC
                > 90
                THEN 'RED'

                ELSE 'GREEN'
            END
        ) STORED,

    recorded_at TIMESTAMPTZ NOT NULL,

    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT facility_current_occupancy_facility_fk
        FOREIGN KEY (facility_id)
        REFERENCES medical_facilities (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT facility_current_occupancy_event_unique
        UNIQUE (last_event_id),

    CONSTRAINT facility_current_occupancy_source_sequence_unique
        UNIQUE (
            source_device_id,
            sequence_number
        ),

    CONSTRAINT facility_current_occupancy_device_not_blank
        CHECK (
            LENGTH(
                BTRIM(source_device_id)
            ) > 0
        ),

    CONSTRAINT facility_current_occupancy_sequence_nonnegative
        CHECK (
            sequence_number >= 0
        ),

    CONSTRAINT facility_current_occupancy_total_positive
        CHECK (
            total_beds > 0
        ),

    CONSTRAINT facility_current_occupancy_occupied_range
        CHECK (
            occupied_beds >= 0
            AND occupied_beds <= total_beds
        ),

    CONSTRAINT facility_current_occupancy_time_order
        CHECK (
            received_at >= recorded_at
        )
);

CREATE INDEX facility_current_occupancy_status_idx
    ON facility_current_occupancy (status);

CREATE INDEX facility_current_occupancy_recorded_at_idx
    ON facility_current_occupancy (recorded_at DESC);


/*
 * ============================================================
 * Facility occupancy history
 * ============================================================
 *
 * Stores every accepted facility occupancy event.
 *
 * Rows older than two days will be deleted by the cleanup
 * function defined at the end of this migration.
 */
CREATE TABLE facility_occupancy_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    event_id UUID NOT NULL,

    facility_id BIGINT NOT NULL,

    source_device_id TEXT NOT NULL,

    sequence_number BIGINT NOT NULL,

    total_beds INTEGER NOT NULL,

    occupied_beds INTEGER NOT NULL,

    available_beds INTEGER
        GENERATED ALWAYS AS (
            total_beds - occupied_beds
        ) STORED,

    occupancy_percentage NUMERIC(7, 4)
        GENERATED ALWAYS AS (
            (
                occupied_beds::NUMERIC
                * 100
            )
            /
            total_beds::NUMERIC
        ) STORED,

    status TEXT
        GENERATED ALWAYS AS (
            CASE
                WHEN (
                    occupied_beds::NUMERIC
                    * 100
                )
                /
                total_beds::NUMERIC
                > 90
                THEN 'RED'

                ELSE 'GREEN'
            END
        ) STORED,

    recorded_at TIMESTAMPTZ NOT NULL,

    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    /*
     * Stores optional additional source data without requiring
     * a new database column for every optional property.
     */
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT facility_occupancy_events_facility_fk
        FOREIGN KEY (facility_id)
        REFERENCES medical_facilities (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT facility_occupancy_events_event_unique
        UNIQUE (event_id),

    /*
     * Prevents the same source sequence from being stored twice.
     */
    CONSTRAINT facility_occupancy_events_source_sequence_unique
        UNIQUE (
            source_device_id,
            sequence_number
        ),

    CONSTRAINT facility_occupancy_events_device_not_blank
        CHECK (
            LENGTH(
                BTRIM(source_device_id)
            ) > 0
        ),

    CONSTRAINT facility_occupancy_events_sequence_nonnegative
        CHECK (
            sequence_number >= 0
        ),

    CONSTRAINT facility_occupancy_events_total_positive
        CHECK (
            total_beds > 0
        ),

    CONSTRAINT facility_occupancy_events_occupied_range
        CHECK (
            occupied_beds >= 0
            AND occupied_beds <= total_beds
        ),

    CONSTRAINT facility_occupancy_events_time_order
        CHECK (
            received_at >= recorded_at
        ),

    CONSTRAINT facility_occupancy_events_payload_object
        CHECK (
            JSONB_TYPEOF(payload) = 'object'
        )
);

CREATE INDEX facility_occupancy_events_facility_time_idx
    ON facility_occupancy_events (
        facility_id,
        recorded_at DESC
    );

CREATE INDEX facility_occupancy_events_device_time_idx
    ON facility_occupancy_events (
        source_device_id,
        recorded_at DESC
    );

CREATE INDEX facility_occupancy_events_status_time_idx
    ON facility_occupancy_events (
        status,
        recorded_at DESC
    );

CREATE INDEX facility_occupancy_events_retention_idx
    ON facility_occupancy_events (recorded_at);


/*
 * ============================================================
 * Ambulance location history
 * ============================================================
 *
 * Stores every accepted ambulance location update.
 *
 * The ambulances table continues to store only the latest
 * location snapshot.
 */
CREATE TABLE ambulance_location_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    event_id UUID NOT NULL,

    ambulance_id BIGINT NOT NULL,

    device_id TEXT NOT NULL,

    sequence_number BIGINT NOT NULL,

    location geometry(Point, 4326) NOT NULL,

    speed_kmh NUMERIC(6, 2),

    heading_degrees NUMERIC(6, 2),

    recorded_at TIMESTAMPTZ NOT NULL,

    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    payload JSONB NOT NULL DEFAULT '{}'::JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ambulance_location_events_ambulance_fk
        FOREIGN KEY (ambulance_id)
        REFERENCES ambulances (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ambulance_location_events_event_unique
        UNIQUE (event_id),

    /*
     * This is the database-level duplicate prevention rule.
     */
    CONSTRAINT ambulance_location_events_device_sequence_unique
        UNIQUE (
            device_id,
            sequence_number
        ),

    CONSTRAINT ambulance_location_events_device_not_blank
        CHECK (
            LENGTH(
                BTRIM(device_id)
            ) > 0
        ),

    CONSTRAINT ambulance_location_events_sequence_nonnegative
        CHECK (
            sequence_number >= 0
        ),

    CONSTRAINT ambulance_location_events_location_valid
        CHECK (
            ST_IsValid(location)
        ),

    CONSTRAINT ambulance_location_events_longitude_range
        CHECK (
            ST_X(location)
            BETWEEN -180 AND 180
        ),

    CONSTRAINT ambulance_location_events_latitude_range
        CHECK (
            ST_Y(location)
            BETWEEN -90 AND 90
        ),

    CONSTRAINT ambulance_location_events_speed_nonnegative
        CHECK (
            speed_kmh IS NULL
            OR speed_kmh >= 0
        ),

    CONSTRAINT ambulance_location_events_heading_range
        CHECK (
            heading_degrees IS NULL
            OR (
                heading_degrees >= 0
                AND heading_degrees < 360
            )
        ),

    CONSTRAINT ambulance_location_events_time_order
        CHECK (
            received_at >= recorded_at
        ),

    CONSTRAINT ambulance_location_events_payload_object
        CHECK (
            JSONB_TYPEOF(payload) = 'object'
        )
);

CREATE INDEX ambulance_location_events_ambulance_time_idx
    ON ambulance_location_events (
        ambulance_id,
        recorded_at DESC
    );

CREATE INDEX ambulance_location_events_device_time_idx
    ON ambulance_location_events (
        device_id,
        recorded_at DESC
    );

CREATE INDEX ambulance_location_events_retention_idx
    ON ambulance_location_events (recorded_at);

CREATE INDEX ambulance_location_events_location_gix
    ON ambulance_location_events
    USING GIST (location);


/*
 * ============================================================
 * Two-day history retention
 * ============================================================
 *
 * Deletes historical occupancy and location events older than
 * two days.
 *
 * Current snapshot tables are not deleted.
 */
CREATE OR REPLACE FUNCTION cleanup_live_monitoring_history()
RETURNS TABLE (
    deleted_occupancy_events BIGINT,
    deleted_ambulance_location_events BIGINT
)
LANGUAGE plpgsql
AS $$
DECLARE
    occupancy_deleted BIGINT;
    ambulance_locations_deleted BIGINT;
BEGIN
    DELETE FROM facility_occupancy_events
    WHERE recorded_at
        < NOW() - INTERVAL '2 days';

    GET DIAGNOSTICS
        occupancy_deleted = ROW_COUNT;

    DELETE FROM ambulance_location_events
    WHERE recorded_at
        < NOW() - INTERVAL '2 days';

    GET DIAGNOSTICS
        ambulance_locations_deleted = ROW_COUNT;

    RETURN QUERY
    SELECT
        occupancy_deleted,
        ambulance_locations_deleted;
END;
$$;