import {
    Activity,
    CircleStop,
    Play,
    RefreshCw,
    RotateCcw,
    Settings2,
    Timer,
    Trash2,
  } from "lucide-react";
  
  import {
    useEffect,
  } from "react";
  
  import {
    useSimulationStore,
  } from "../../stores/simulationStore.js";
  
  import "../../styles/simulation-control-panel.css";
  
  function formatDateTime(
    value,
  ) {
    if (!value) {
      return "Not available";
    }
  
    const date =
      new Date(
        value,
      );
  
    if (
      Number.isNaN(
        date.getTime(),
      )
    ) {
      return "Not available";
    }
  
    return new Intl.DateTimeFormat(
      "en-GB",
      {
        dateStyle:
          "medium",
  
        timeStyle:
          "medium",
      },
    ).format(
      date,
    );
  }
  
  function SimulationControlPanel({
    onResetComplete,
  }) {
    const status =
      useSimulationStore(
        (state) =>
          state.status,
      );
  
    const actionStatus =
      useSimulationStore(
        (state) =>
          state.actionStatus,
      );
  
    const error =
      useSimulationStore(
        (state) =>
          state.error,
      );
  
    const simulation =
      useSimulationStore(
        (state) =>
          state.simulation,
      );
  
    const settings =
      useSimulationStore(
        (state) =>
          state.settings,
      );
  
    const setSetting =
      useSimulationStore(
        (state) =>
          state.setSetting,
      );
  
    const resetSettings =
      useSimulationStore(
        (state) =>
          state.resetSettings,
      );
  
    const loadStatus =
      useSimulationStore(
        (state) =>
          state.loadStatus,
      );
  
    const start =
      useSimulationStore(
        (state) =>
          state.start,
      );
  
    const stop =
      useSimulationStore(
        (state) =>
          state.stop,
      );

    const resetOperations =
      useSimulationStore(
        (state) =>
          state.resetOperations,
      );
  
    useEffect(() => {
      const controller =
        new AbortController();
  
      void loadStatus({
        signal:
          controller.signal,
      }).catch(() => {
        // Error is displayed through Zustand.
      });
  
      return () => {
        controller.abort();
      };
    }, [
      loadStatus,
    ]);
  
    /*
     * The Backend currently does not publish simulation tick
     * status through Socket.IO, so the panel refreshes its small
     * status payload every two seconds.
     */
    useEffect(() => {
      const intervalId =
        window.setInterval(
          () => {
            void loadStatus({
              silent:
                true,
            }).catch(() => {
              // Keep the last valid status visible.
            });
          },
          2000,
        );
  
      return () => {
        window.clearInterval(
          intervalId,
        );
      };
    }, [
      loadStatus,
    ]);
  
    const isRunning =
      Boolean(
        simulation
          ?.isRunning,
      );
  
    const isLoading =
      status ===
      "loading";
  
    const isStarting =
      actionStatus ===
      "starting";
  
    const isStopping =
      actionStatus ===
      "stopping";

    const isResetting =
      actionStatus ===
      "resetting";
  
    const isActionPending =
    isStarting ||
    isStopping ||
    isResetting;
  
    const activeRun =
      simulation
        ?.activeRun ??
      null;
  
    const displayedRun =
      activeRun ??
      simulation
        ?.latestRun ??
      null;
  
    function updateNumericSetting(
      settingName,
      event,
    ) {
      const numericValue =
        Number(
          event.target.value,
        );
  
      setSetting(
        settingName,
        numericValue,
      );
    }
  
    async function handleStart() {
      try {
        await start();
      } catch {
        // Store exposes the error.
      }
    }
  
    async function handleStop() {
      try {
        await stop();
      } catch {
        // Store exposes the error.
      }
    }

    async function handleResetOperations() {
        const confirmed =
          window.confirm(
            [
              "Reset all operational data generated by the simulation?",
              "",
              "This will remove simulated emergencies, alerts, recommendations, dispatches and routes.",
              "Users, facilities, governorates and core ambulance records will remain.",
            ].join("\n"),
          );
      
        if (!confirmed) {
          return;
        }
      
        try {
          const result =
            await resetOperations();
      
          if (
            result &&
            typeof onResetComplete ===
              "function"
          ) {
            await onResetComplete();
          }
        } catch {
          // Error is displayed through Zustand.
        }
      }
  
    async function handleRefresh() {
      try {
        await loadStatus();
      } catch {
        // Store exposes the error.
      }
    }
  
    return (
      <section className="simulation-panel">
        <header className="simulation-panel__header">
          <div className="simulation-panel__title">
            <div className="simulation-panel__icon">
              <Activity size={22} />
            </div>
  
            <div>
              <span>
                Dynamic data feed
              </span>
  
              <h2>
                Simulation Control
              </h2>
  
              <p>
                Generate live occupancy,
                emergency and ambulance
                movement scenarios.
              </p>
            </div>
          </div>
  
          <div
            className={`simulation-panel__status ${
              isRunning
                ? "simulation-panel__status--running"
                : "simulation-panel__status--stopped"
            }`}
          >
            <span />
  
            {isRunning
              ? "Running"
              : "Stopped"}
          </div>
        </header>
  
        {error && (
          <div className="simulation-panel__error">
            <strong>
              Simulation request failed
            </strong>
  
            <span>
              {error}
            </span>
          </div>
        )}
  
        <div className="simulation-panel__body">
          <div className="simulation-panel__settings">
            <div className="simulation-panel__section-heading">
              <Settings2 size={18} />
  
              <div>
                <strong>
                  Runtime Settings
                </strong>
  
                <span>
                  Changes apply to the next
                  simulation run.
                </span>
              </div>
            </div>
  
            <div className="simulation-panel__fields">
              <label>
                <span>
                  Tick Interval
                </span>
  
                <div className="simulation-panel__input-unit">
                  <input
                    type="number"
                    min="500"
                    max="60000"
                    step="100"
                    value={
                      settings
                        .tickIntervalMs
                    }
                    disabled={
                      isRunning
                    }
                    onChange={(event) =>
                      updateNumericSetting(
                        "tickIntervalMs",
                        event,
                      )
                    }
                  />
  
                  <small>
                    ms
                  </small>
                </div>
              </label>
  
              <label>
                <span>
                  Occupancy Every
                </span>
  
                <div className="simulation-panel__input-unit">
                  <input
                    type="number"
                    min="1"
                    max="3600"
                    value={
                      settings
                        .occupancyEveryTicks
                    }
                    disabled={
                      isRunning
                    }
                    onChange={(event) =>
                      updateNumericSetting(
                        "occupancyEveryTicks",
                        event,
                      )
                    }
                  />
  
                  <small>
                    ticks
                  </small>
                </div>
              </label>
  
              <label>
                <span>
                  Emergency Every
                </span>
  
                <div className="simulation-panel__input-unit">
                  <input
                    type="number"
                    min="1"
                    max="3600"
                    value={
                      settings
                        .emergencyEveryTicks
                    }
                    disabled={
                      isRunning
                    }
                    onChange={(event) =>
                      updateNumericSetting(
                        "emergencyEveryTicks",
                        event,
                      )
                    }
                  />
  
                  <small>
                    ticks
                  </small>
                </div>
              </label>
  
              <label>
                <span>
                  Movement Every
                </span>
  
                <div className="simulation-panel__input-unit">
                  <input
                    type="number"
                    min="1"
                    max="60"
                    value={
                      settings
                        .ambulanceMovementEveryTicks
                    }
                    disabled={
                      isRunning
                    }
                    onChange={(event) =>
                      updateNumericSetting(
                        "ambulanceMovementEveryTicks",
                        event,
                      )
                    }
                  />
  
                  <small>
                    ticks
                  </small>
                </div>
              </label>
  
              <label>
                <span>
                  Maximum Emergencies
                </span>
  
                <div className="simulation-panel__input-unit">
                  <input
                    type="number"
                    min="1"
                    max="20"
                    value={
                      settings
                        .maxActiveEmergencies
                    }
                    disabled={
                      isRunning
                    }
                    onChange={(event) =>
                      updateNumericSetting(
                        "maxActiveEmergencies",
                        event,
                      )
                    }
                  />
  
                  <small>
                    cases
                  </small>
                </div>
              </label>
  
              <label className="simulation-panel__checkbox">
                <input
                  type="checkbox"
                  checked={
                    settings
                      .autoConfirmDispatch
                  }
                  disabled={
                    isRunning
                  }
                  onChange={(event) => {
                    setSetting(
                      "autoConfirmDispatch",
                      event.target.checked,
                    );
                  }}
                />
  
                <div>
                  <strong>
                    Auto-confirm Dispatch
                  </strong>
  
                  <span>
                    Automatically assign the
                    nearest eligible ambulance.
                  </span>
                </div>
              </label>
            </div>
          </div>
  
          <div className="simulation-panel__runtime">
            <div className="simulation-panel__section-heading">
              <Timer size={18} />
  
              <div>
                <strong>
                  Runtime Status
                </strong>
  
                <span>
                  Latest Backend simulation
                  state.
                </span>
              </div>
            </div>
  
            <dl className="simulation-panel__metrics">
              <div>
                <dt>
                  Run ID
                </dt>
  
                <dd>
                  {displayedRun
                    ?.id ??
                    "—"}
                </dd>
              </div>
  
              <div>
                <dt>
                  Tick Count
                </dt>
  
                <dd>
                  {displayedRun
                    ?.tickCount ??
                    0}
                </dd>
              </div>
  
              <div>
                <dt>
                  Process Timer
                </dt>
  
                <dd>
                  {simulation
                    ?.processTimerActive
                    ? "Active"
                    : "Inactive"}
                </dd>
              </div>
  
              <div>
                <dt>
                  Last Tick
                </dt>
  
                <dd>
                  {formatDateTime(
                    simulation
                      ?.lastTickAt,
                  )}
                </dd>
              </div>
  
              <div>
                <dt>
                  Started
                </dt>
  
                <dd>
                  {formatDateTime(
                    simulation
                      ?.startedAt,
                  )}
                </dd>
              </div>
  
              <div>
                <dt>
                  Latest Run Status
                </dt>
  
                <dd>
                  {displayedRun
                    ?.status ??
                    "Not started"}
                </dd>
              </div>
            </dl>
          </div>
        </div>
        <footer className="simulation-panel__footer">
  <button
    type="button"
    className="simulation-panel__button simulation-panel__button--danger"
    onClick={
      handleResetOperations
    }
    disabled={
      isRunning ||
      isActionPending
    }
  >
    <Trash2 size={16} />

    {isResetting
      ? "Resetting..."
      : "Reset Simulation Data"}
  </button>

  <button
    type="button"
    className="simulation-panel__button simulation-panel__button--secondary"
    onClick={
      resetSettings
    }
    disabled={
      isRunning ||
      isActionPending
    }
  >
    <RotateCcw size={16} />

    Reset Settings
  </button>

  <button
    type="button"
    className="simulation-panel__button simulation-panel__button--secondary"
    onClick={
      handleRefresh
    }
    disabled={
      isLoading ||
      isActionPending
    }
  >
    <RefreshCw
      size={16}
      className={
        isLoading
          ? "simulation-panel__spinner"
          : undefined
      }
    />

    Refresh Status
  </button>

  {isRunning ? (
    <button
      type="button"
      className="simulation-panel__button simulation-panel__button--stop"
      onClick={
        handleStop
      }
      disabled={
        isActionPending
      }
    >
      <CircleStop size={17} />

      {isStopping
        ? "Stopping..."
        : "Stop Simulation"}
    </button>
  ) : (
    <button
      type="button"
      className="simulation-panel__button simulation-panel__button--start"
      onClick={
        handleStart
      }
      disabled={
        isActionPending
      }
    >
      <Play size={17} />

      {isStarting
        ? "Starting..."
        : "Start Simulation"}
    </button>
  )}
</footer>
      </section>
    );
  }
  
  export default SimulationControlPanel;